rocksdb:
  write_buffer_size: 67108864  # 64MB
  max_write_buffer_number: 3
  min_write_buffer_number_to_merge: 1
  compression: lz4
  compression_level: 4
  block_cache_size: 268435456  # 256MB
  bloom_filter_bits_per_key: 10
  max_background_jobs: 2
  bytes_per_sync: 1048576  # 1MB
  max_background_compactions: 4
  max_background_flushes: 2